[package]
version = "0.1.0"
name = "flea-market"
repository = "https://github.com/seed-rs/seed-quickstart"
authors = ["MaryEaston <masae904@icloud.com>"]
description = "App Description"
categories = ["category"]
license = "MIT"
readme = "./README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.18"

[dependencies]
seed = "0.8.0"
wee_alloc = "*"
plotters = "*"
plotters-canvas = "*"
web-sys = "*"
chrono = "*"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
